pipeline {
	agent { label 'ActiveDirectory' } 
	triggers { cron('*/5 * * * *') }   
	stages {
        stage('DoThatThing') {
            steps {
                bat "powershell.exe -NonInteractive -ExecutionPolicy Bypass -Command \"& '.\\YourScript.ps1'\""
            }
        }
    }
}
